#!/usr/bin/env node
// structured_cfg.js
//
// Reconstruct a structured-pseudocode view of an AGE-engine disassembled script
// (src/*.txt). Pipeline:
//
//   1. Parse the disassembly text into instructions, resolving `label_XXXX` names
//      to instruction indexes.
//   2. Split into basic blocks at every control-flow boundary (jump/jump-cond/call
//      targets AND immediately after each control instruction) and build the
//      control-flow graph (CFG).
//   3. Compute dominators / postdominators (iterative fixpoint) and detect natural
//      loops from back edges.
//   4. Structurally analyse the reducible CFG (the AGE bytecode is compiler output,
//      so the overwhelming majority of scripts are reducible) into an AST of
//      sequences / if / if-else / while / do-while, with `break`/`continue`/`goto`
//      fallback for whatever does not fit a schema.
//   5. Pretty-print the AST as readable pseudocode (or emit DOT / JSON for the CFG).
//
// The AGE `jcc` is a two-target conditional jump:
//     jcc cond A B   ->  if (cond != 0) { if A != ffffffff goto A; else fallthrough }
//                         else          { if B != ffffffff goto B; else fallthrough }
// `0xFFFFFFFF` means "this branch does not jump / falls through". `jmp L` = goto L.
//
// Because the engine's bytecode is generated by a compiler, the CFGs are almost
// always reducible and structure cleanly into if/while. Anything that does not
// cleanly reduce is emitted as an explicit `label:`+`goto` so the output is always
// a faithful, valid rendering of the original flow.
//
// Usage:
//   node re/structured_cfg.js <src-file.txt> [--dot out.dot] [--json out.json] [--raw]
//   node re/structured_cfg.js --dir src [--out output/ --suffix .struct.txt]
//
// Exit codes: 0 ok, 1 bad args / parse failure, 2 unrecoverable error.

import fs from 'node:fs';
import path from 'node:path';

// ---------------------------------------------------------------------------
// Tokenizing & instruction parsing
// ---------------------------------------------------------------------------

// Strip `// line comments` and `/* block */` comments, but not ones inside "..." strings.
function stripComments(s) {
  let out = '';
  let inStr = false;
  let inBlock = false;
  for (let i = 0; i < s.length; i++) {
    const c = s[i];
    const n = s[i + 1];
    if (inBlock) {
      if (c === '*' && n === '/') { inBlock = false; i++; }
      continue;
    }
    if (inStr) {
      out += c;
      if (c === '"') inStr = false;
      continue;
    }
    if (c === '"') { inStr = true; out += c; continue; }
    if (c === '/' && n === '*') { inBlock = true; i++; continue; }
    if (c === '/' && n === '/') break; // line comment to end
    out += c;
  }
  return out;
}

// Split a line into tokens. Parenthesised groups `( x y )` and double-quoted
// strings are kept as single tokens; otherwise whitespace separates tokens.
function tokenize(s) {
  s = stripComments(s).trim();
  const toks = [];
  let i = 0;
  while (i < s.length) {
    while (i < s.length && /\s/.test(s[i])) i++;
    if (i >= s.length) break;
    let cur = '';
    const c0 = s[i];
    if (c0 === '(') {
      let depth = 0;
      while (i < s.length) {
        const c = s[i];
        cur += c;
        if (c === '(') depth++;
        else if (c === ')') { depth--; if (depth === 0) { i++; break; } }
        i++;
      }
    } else if (c0 === '"') {
      cur = '"';
      i++;
      while (i < s.length && s[i] !== '"') { cur += s[i]; i++; }
      cur += '"';
      i++;
      // If there is no closing quote, still accept what we have (tolerant).
      if (s[i - 1] !== '"') cur += '"';
    } else {
      while (i < s.length && !/\s/.test(s[i])) { cur += s[i]; i++; }
    }
    toks.push(cur);
  }
  return toks;
}

function isHeaderLine(line) {
  const t = line.trim();
  return t.startsWith('==') || t.startsWith('signature') || t.startsWith('local_vars');
}

// Unpack a token into {kind, ...} for easier handling.
// Kinds: local (int/ptr/string), global (int/ptr/string), imm (number/hex),
//        label, immstr, rawword.
function classify(tok) {
  if (tok.startsWith('label_')) return { kind: 'label', name: tok };
  let m = /^\(local-(int|ptr|string|float-ptr|float) ([0-9a-fA-F]+)\)$/.exec(tok);
  if (m) return { kind: 'local', type: m[1], idx: parseInt(m[2], 16) };
  m = /^\(global-(int|ptr|string|float-ptr|float) ([0-9a-fA-F]+)\)$/.exec(tok);
  if (m) return { kind: 'global', type: m[1], idx: parseInt(m[2], 16) };
  if (tok.startsWith('"')) return { kind: 'str', raw: tok };
  if (/^0x[0-9a-fA-F]+$/.test(tok)) return { kind: 'imm', raw: tok, val: parseInt(tok, 16) };
  if (/^[0-9a-fA-F]+$/.test(tok)) return { kind: 'imm', raw: tok, val: parseInt(tok, 16) };
  return { kind: 'word', raw: tok };
}

// Operand display: prefix = first letter of each word in the type, index/value in
// hexadecimal (matching the source disassembly), e.g.
//   (local-int N)  -> li[N]    (local-ptr N)  -> lp[N]    (local-string N) -> ls[N]
//   (global-int X) -> gi[X]    (global-ptr X) -> gp[X]    (global-string X) -> gs[X]
function opName(op) {
  const LOCAL = { int: 'li', ptr: 'lp', string: 'ls', float: 'lf', 'float-ptr': 'lfp' };
  const GLOBAL = { int: 'gi', ptr: 'gp', string: 'gs', float: 'gf', 'float-ptr': 'gfp' };
  switch (op.kind) {
    case 'local': return `${LOCAL[op.type] || 'l'}[${op.idx.toString(16)}]`;
    case 'global': return `${GLOBAL[op.type] || 'g'}[${op.idx.toString(16)}]`;
    case 'imm': return (op.raw === 'ffffffff') ? '-1' : op.raw;
    case 'label': return op.name;
    case 'str': return op.raw;
    default: return op.raw;
  }
}

// ---------------------------------------------------------------------------
// Symbolic rewriting of known data-processing instructions
// ---------------------------------------------------------------------------
// The first operand is the destination; for value-producing ops we render
//   MNEM d a b  ->  d = <a op b>      e.g. eq a b c -> a = b == c
//   mov d s     ->  d = s
// "full" ops mutate in place (bit-set/bit-reset), rendered specially. Any op whose
// argument count does not match its expected shape is recorded as "unexpected" and
// left verbatim (never rewritten), per the request.

const DATA_OPS = new Map([
  ['mov',      { n: 2, rhs: (a) => `${a[1]}` }],
  ['add',      { n: 3, rhs: (a) => `${a[1]} + ${a[2]}` }],
  ['sub',      { n: 3, rhs: (a) => `${a[1]} - ${a[2]}` }],
  ['mul',      { n: 3, rhs: (a) => `${a[1]} * ${a[2]}` }],
  ['div',      { n: 3, rhs: (a) => `${a[1]} / ${a[2]}` }],
  ['mod',      { n: 3, rhs: (a) => `${a[1]} % ${a[2]}` }],
  ['and',      { n: 3, rhs: (a) => `${a[1]} & ${a[2]}` }],
  ['or',       { n: 3, rhs: (a) => `${a[1]} | ${a[2]}` }],
  ['sar',      { n: 3, rhs: (a) => `${a[1]} >> ${a[2]}` }],
  ['shl',      { n: 3, rhs: (a) => `${a[1]} << ${a[2]}` }],
  ['eq',       { n: 3, rhs: (a) => `${a[1]} == ${a[2]}` }],
  ['ne',       { n: 3, rhs: (a) => `${a[1]} != ${a[2]}` }],
  ['lt',       { n: 3, rhs: (a) => `${a[1]} < ${a[2]}` }],
  ['lte',      { n: 3, rhs: (a) => `${a[1]} <= ${a[2]}` }],
  ['gr',       { n: 3, rhs: (a) => `${a[1]} > ${a[2]}` }],
  ['gre',      { n: 3, rhs: (a) => `${a[1]} >= ${a[2]}` }],
  ['random',   { n: 2, rhs: (a) => `rand() % ${a[1]}` }],
  ['lea',      { n: 2, rhs: (a) => `&${a[1]}` }],
  // bit ops (n are bit indices, verified from sub_42F8B0 / sub_42F920 / sub_42FB40):
  //   bit-set   d b -> d |= (1 << b)          (= 0x135)
  //   bit-reset d b -> d &= ~(1 << b)         (= 0x136)
  //   check-bit d s b -> d = ((1 << b) & s) != 0 (= 0x13F)
  ['bit-set',  { n: 2, full: (a) => `${a[0]} |= (1 << ${a[1]})` }],
  ['bit-reset',{ n: 2, full: (a) => `${a[0]} &= ~(1 << ${a[1]})` }],
  ['check-bit',{ n: 3, rhs: (a) => `((1 << ${a[2]}) & ${a[1]}) != 0` }],
]);

// Record instructions whose shape/arity does not match expectation (kept verbatim).
// Each entry aggregates count + one example (with the file it first appeared in), so
// they can be audited. `CURRENT_FILE` is the file being analysed at the time.
let CURRENT_FILE = null;
const unexpected = new Map();
function recordUnexpected(inst, expected) {
  const key = `${inst.mnem}(${inst.args.length} args, expected ${expected})`;
  const e = unexpected.get(key);
  if (e) { e.count++; }
  else { unexpected.set(key, { count: 1, example: inst.raw, file: CURRENT_FILE }); }
}

const localSlot = (op) => (op.kind === 'local') ? op.idx : null;

// Symbolic form of a straight-line data instruction, or null if it is not a known
// data op / its arity is unexpected (in which case it is recorded and left verbatim).
function symbolicInst(inst) {
  const def = DATA_OPS.get(inst.mnem);
  if (!def) return null;
  if (inst.argsCls.length !== def.n) { recordUnexpected(inst, def.n); return null; }
  const a = inst.argsCls.map(opName);
  return def.full ? def.full(a) : `${a[0]} = ${def.rhs(a)}`;
}

// The right-hand side of a value-producing data op (used when folding an assignment
// into an if/while condition). Returns null for modifier ops / mismatches.
function symbolicRHS(inst) {
  const def = DATA_OPS.get(inst.mnem);
  if (!def || def.full) return null;
  if (inst.argsCls.length !== def.n) { recordUnexpected(inst, def.n); return null; }
  return def.rhs(inst.argsCls.map(opName));
}

// The instruction immediately before a `jcc` that directly assigns the tested
// variable (same local slot), if it is a foldable value-producing data op.
function findFoldable(ctrl, head) {
  if (!head || !head.length) return null;
  const last = head[head.length - 1];
  const def = DATA_OPS.get(last.mnem);
  if (!def || def.full) return null;
  if (last.argsCls.length !== def.n) return null;
  const condSlot = localSlot(ctrl.argsCls[0]);
  const dstSlot = localSlot(last.argsCls[0]);
  if (condSlot == null || dstSlot == null || dstSlot !== condSlot) return null;
  return last;
}

// Statefully strip ALL comments across the whole text, correctly handling
// MULTI-LINE `/* ... */` block comments and `//` line comments, and never touching
// text inside `"..."` strings. AGE scripts use `/* 原文存档（对照用，不参与汇编）... */`
// blocks that wrap MULTIPLE original text lines; a per-line stripper would leak
// those lines into the instruction stream. This pre-pass is the fix.
function stripAllComments(text) {
  let out = '';
  let inStr = false;
  let inBlock = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    const n = text[i + 1];
    if (inBlock) {
      if (c === '*' && n === '/') { inBlock = false; i++; }
      continue;
    }
    if (inStr) {
      out += c;
      if (c === '"') inStr = false;
      continue;
    }
    if (c === '"') { inStr = true; out += c; continue; }
    if (c === '/' && n === '*') { inBlock = true; i++; continue; }
    if (c === '/' && n === '/') { // line comment -> drop to end of line
      while (i < text.length && text[i] !== '\n') i++;
      out += '\n';
      continue;
    }
    out += c;
  }
  return out;
}

function parse(text) {
  text = stripAllComments(text);
  const lines = text.split(/\r?\n/);
  const insts = [];
  const labelOf = new Map(); // label name -> instruction index
  const pendingLabels = [];
  let locals = null;
  for (const raw of lines) {
    const line = raw.trimEnd();
    if (!line.trim()) continue;
    if (isHeaderLine(line)) {
      const m = /^local_vars\s*=\s*\{(.*)\}/.exec(line.trim());
      if (m) locals = m[1].trim().split(/\s+/).filter(Boolean);
      continue;
    }
    const toks = tokenize(line);
    if (toks.length === 0) continue;
    // Collect any leading label definitions on this line.
    let idx = 0;
    while (idx < toks.length && toks[idx].startsWith('label_')) {
      pendingLabels.push(toks[idx]);
      idx++;
    }
    if (idx >= toks.length) continue; // line was only labels
    const mnem = toks[idx];
    const args = toks.slice(idx + 1);
    const iidx = insts.length;
    for (const lab of pendingLabels) labelOf.set(lab, iidx);
    pendingLabels.length = 0;
    insts.push({ mnem, args, raw: line, idx: iidx, argsCls: args.map(classify) });
  }
  // Any labels at EOF with no following instruction map to a sentinel.
  for (const lab of pendingLabels) labelOf.set(lab, insts.length);
  return { locals, insts, labelOf };
}

// ---------------------------------------------------------------------------
// Basic blocks & CFG
// ---------------------------------------------------------------------------

const TERMINATORS = new Set(['jmp', 'jcc', 'call', 'exit', 'exit-script', 'ret', 'call-script']);

function buildBlocks(sc) {
  const n = sc.insts.length;
  const labelTargets = new Set();
  for (const v of sc.labelOf.values()) labelTargets.add(v);

  // Plain label targets must be leaders.
  let leaders = new Set(labelTargets);
  leaders.add(0);

  // Jump/branch targets are leaders (== label targets already).
  // Instruction immediately after a control instruction is a leader (split point).
  for (let i = 0; i < n; i++) {
    const it = sc.insts[i];
    const m = it.mnem;
    if (TERMINATORS.has(m)) {
      leaders.add(i + 1);
      // Record intra-script call targets as leaders too (labels already cover).
    }
    if (m === 'jmp' || m === 'jcc' || m === 'call') {
      for (const a of it.args) {
        if (a.startsWith('label_') && sc.labelOf.has(a)) leaders.add(sc.labelOf.get(a));
      }
    }
  }
  leaders.delete(n); // beyond end
  const sorted = [...leaders].sort((a, b) => a - b);

  // Assign each leader an index; a block owns [leader, nextLeader).
  const blocks = [];
  const blockOfInstr = new Array(n).fill(-1);
  for (let k = 0; k < sorted.length; k++) {
    const start = sorted[k];
    const end = (k + 1 < sorted.length) ? sorted[k + 1] : n;
    const bid = blocks.length;
    const insts = [];
    for (let i = start; i < end; i++) { insts.push(sc.insts[i]); blockOfInstr[i] = bid; }
    const block = { id: bid, start, end, insts, preds: new Set(), succs: new Set(), follow: null, branches: null, labelNames: [] };
    blocks.push(block);
  }
  // Attach label names to the block they point at.
  for (const [name, iidx] of sc.labelOf) {
    if (iidx < n && blockOfInstr[iidx] >= 0) {
      blocks[blockOfInstr[iidx]].labelNames.push(name);
    }
  }

  // Build edges.
  const blockedBy = (iidx) => (iidx >= 0 && iidx < n) ? blockOfInstr[iidx] : null;
  const fallThroughOf = (bid) => {
    const b = blocks[bid];
    if (b.end >= n) return null; // last block, no fall-through
    return blockedBy(b.end);
  };
  for (const b of blocks) {
    const last = b.insts[b.insts.length - 1];
    const m = last.mnem;
    if (m === 'jmp') {
      const t = last.args[0];
      const tgt = sc.labelOf.has(t) ? blockedBy(sc.labelOf.get(t)) : null;
      if (tgt != null) b.succs.add(tgt);
      b.follow = tgt;
    } else if (m === 'jcc') {
      const cond = last.argsCls[0];
      const a = last.args[1];
      const bb = last.args[2];
      const trueTarget = a === 'ffffffff' ? null : (sc.labelOf.has(a) ? blockedBy(sc.labelOf.get(a)) : null);
      const falseTarget = bb === 'ffffffff' ? null : (sc.labelOf.has(bb) ? blockedBy(sc.labelOf.get(bb)) : null);
      const ft = fallThroughOf(b.id);
      const t = trueTarget == null ? ft : trueTarget;
      const f = falseTarget == null ? ft : falseTarget;
      b.branches = { cond, trueBlock: t, falseBlock: f };
      if (t != null) b.succs.add(t);
      if (f != null) b.succs.add(f);
      b.follow = ft;
    } else if (m === 'call') {
      // Intra-script subroutine call: fall-through is the return address;
      // the target is handled as a separate procedure root.
      b.follow = fallThroughOf(b.id);
      if (b.follow != null) b.succs.add(b.follow);
      const t = last.args[0];
      b.callTarget = sc.labelOf.has(t) ? blockedBy(sc.labelOf.get(t)) : null;
    } else if (m === 'exit' || m === 'exit-script' || m === 'ret') {
      b.follow = null;
    } else if (m === 'call-script') {
      // Call another script: it is a statement; fall-through continues.
      b.follow = fallThroughOf(b.id);
      if (b.follow != null) b.succs.add(b.follow);
    } else {
      // Plain block: falls through to the next block.
      b.follow = fallThroughOf(b.id);
      if (b.follow != null) b.succs.add(b.follow);
    }
  }
  // Compute predecessors.
  for (const b of blocks) for (const s of b.succs) blocks[s].preds.add(b.id);
  return { blocks, blockOfInstr };
}

// ---------------------------------------------------------------------------
// Dominators / postdominators
// ---------------------------------------------------------------------------
// Fast (Cooper-Harvey-Kennedy style) dominance with BigInt bitsets. One bit per
// node (index = reverse-postorder position). Intersections are word-level ANDs,
// so this scales well even for multi-thousand-node procedure CFGs.

// Reverse postorder (RPO) of the nodes reachable from `entry` via succsOf.
// In RPO the dominators of a node always appear before it.
function rpo(nodes, entry, succsOf) {
  const inSet = new Set(nodes);
  const visited = new Set([entry]);
  const post = [];
  const stack = [{ node: entry, idx: 0 }];
  while (stack.length) {
    const top = stack[stack.length - 1];
    const succs = succsOf(top.node).filter(s => inSet.has(s));
    if (top.idx < succs.length) {
      const s = succs[top.idx++];
      if (!visited.has(s)) { visited.add(s); stack.push({ node: s, idx: 0 }); }
    } else {
      post.push(top.node);
      stack.pop();
    }
  }
  post.reverse(); // RPO (entry first)
  return post;
}

function computeDominators(nodes, entry, succsOf) {
  const order = rpo(nodes, entry, succsOf);
  const index = new Map();
  order.forEach((id, i) => index.set(id, i));
  const N = order.length;
  const ONE = 1n;
  const ALL = (ONE << BigInt(N)) - 1n;
  const pred = new Map();
  for (const id of order) pred.set(id, []);
  for (const id of order) {
    for (const s of succsOf(id)) if (index.has(s)) pred.get(s).push(id);
  }
  const dom = new Map();
  for (const id of order) dom.set(id, ALL);
  dom.set(entry, ONE << BigInt(index.get(entry)));
  let changed = true;
  while (changed) {
    changed = false;
    for (const id of order) {
      if (id === entry) continue;
      const ps = pred.get(id);
      if (ps.length === 0) continue;
      let nd = dom.get(ps[0]);
      for (let k = 1; k < ps.length; k++) nd &= dom.get(ps[k]);
      nd |= ONE << BigInt(index.get(id));
      if (nd !== dom.get(id)) { dom.set(id, nd); changed = true; }
    }
  }
  return { dom, index, order, N };
}

// Build the dominator map (id -> idom) from a bitset dom result, plus depths.
function computeIdom(domInfo) {
  const { dom, index, order, N } = domInfo;
  const ONE = 1n;
  const idom = new Map();
  const depth = new Map();
  for (const id of order) {
    if (id === order[0]) { depth.set(id, 0); continue; }
    const ownBit = ONE << BigInt(index.get(id));
    let bits = dom.get(id) & ~ownBit; // strict dominators
    let best = order[0];
    let bestDepth = -1;
    while (bits) {
      const low = bits & -bits;
      const i = low.toString(2).length - 1;
      const d = order[i];
      const dd = (depth.get(d) ?? 0);
      if (dd > bestDepth) { bestDepth = dd; best = d; }
      bits ^= low;
    }
    idom.set(id, best);
    depth.set(id, bestDepth + 1);
  }
  return idom;
}

function dominates(domInfo, a, b) {
  // does a dominate b? (bit a set in dom[b])
  if (!domInfo.index.has(a) || !domInfo.index.has(b)) return false;
  return ((domInfo.dom.get(b) >> BigInt(domInfo.index.get(a))) & 1n) !== 0n;
}

// Virtual exit node used during postdominance analysis. Never a real block id.
const EXIT = '__exit__';

// Postdominators: x post-dominates y iff every path y -> exit passes through x.
// Computed by adding a virtual EXIT node (reachable from every terminal block in the
// reversed graph) and computing dominators on the reversed graph rooted at EXIT.
function computePostdominators(nodes, succsOf) {
  const all = [EXIT, ...nodes];
  // Reversed adjacency: original edge u->v becomes v->u. Also EXIT -> terminal(original).
  const rsucc = new Map();
  for (const id of all) rsucc.set(id, []);
  for (const u of nodes) {
    for (const v of succsOf(u)) rsucc.get(v)?.push(u);
    if (succsOf(u).length === 0) rsucc.get(EXIT).push(u); // EXIT -> terminal (reversed)
  }
  const domInfo = computeDominators(all, EXIT, (id) => rsucc.get(id) || []);
  const ipdom = computeIdom(domInfo);
  return { dom: domInfo.dom, ipdom, domInfo };
}

// ---------------------------------------------------------------------------
// Natural loops
// ---------------------------------------------------------------------------

function findNaturalLoops(blocks, entry, succsOf, domInfo) {
  const nodes = [...domInfo.index.keys()]; // procedure members (RPO set)
  const succ = new Map();
  const pred = new Map();
  for (const id of nodes) { succ.set(id, succsOf(id)); }
  for (const id of nodes) {
    if (!pred.has(id)) pred.set(id, []);
    for (const s of succ.get(id)) {
      if (!pred.has(s)) pred.set(s, []);
      pred.get(s).push(id);
    }
  }
  // header -> loop node set
  const loops = new Map();
  for (const u of nodes) {
    for (const v of succ.get(u) || []) {
      if (v === u) {
        // self-loop
        if (!loops.has(v)) loops.set(v, new Set([v]));
        continue;
      }
      // Back edge u->v iff v dominates u (i.e. dom[u] contains v).
      if (dominates(domInfo, v, u)) {
        const loop = new Set([u, v]);
        const work = [u];
        while (work.length) {
          const x = work.pop();
          for (const p of pred.get(x) || []) {
            if (p === v) continue;
            if (!loop.has(p)) { loop.add(p); work.push(p); }
          }
        }
        if (!loops.has(v)) loops.set(v, new Set());
        for (const x of loop) loops.get(v).add(x);
      }
    }
  }
  return loops;
}

// ---------------------------------------------------------------------------
// Region helpers
// ---------------------------------------------------------------------------

// Distinct exit targets of a loop: flow successors of loop nodes that are outside it.
function loopExits(blocks, loopSet, succsOf) {
  const exits = new Set();
  for (const id of loopSet) {
    for (const s of succsOf(id)) {
      if (!loopSet.has(s)) exits.add(s);
    }
  }
  return exits;
}

// BFS over flow edges from `entry`, stopping at any block in `stops`.
// Returns { nodes:Set, reachable:boolean } where reachable=false means entry is already a stop.
function collectRegion(entry, stops, succsOf) {
  const nodes = new Set();
  if (stops.has(entry)) return { nodes, reachable: false, direct: true };
  const work = [entry];
  nodes.add(entry);
  while (work.length) {
    const x = work.pop();
    for (const s of succsOf(x)) {
      if (stops.has(s) || nodes.has(s)) continue;
      nodes.add(s);
      work.push(s);
    }
  }
  return { nodes, reachable: true };
}

// ---------------------------------------------------------------------------
// Condition inlining (peephole expression reconstruction)
// ---------------------------------------------------------------------------

// Condition for a `jcc`: reference the operand that holds the tested value.
// We do NOT reconstruct/re-inline the boolean expression that computed it — the
// side-effecting instructions (eq/and/... written to that variable) are kept as
// separate statements (two-step form), and the branch test just names the variable.
const condForJcc = (inst) => opName(inst.argsCls[0]);

// Negate a condition (used for the "false branch is the body" / inverted jumps).
// `cond` is already a simple operand name (e.g. `li[2]`); Python-style `not`.
function negCond(cond) {
  return `not ${cond}`;
}

// ---------------------------------------------------------------------------
// Statement rendering
// ---------------------------------------------------------------------------

function renderInst(inst, options) {
  // Known data-processing instructions are rewritten symbolically; everything else
  // (and any unexpected shape) is kept verbatim.
  const sym = symbolicInst(inst);
  if (sym != null) return sym;
  const parts = inst.argsCls.map(opName);
  return `${inst.mnem} ${parts.join(' ')}`.trim();
}

// NOTE: renderer defined below after AST building; these are helper templates.

// ---------------------------------------------------------------------------
// CFG procedure extraction
// ---------------------------------------------------------------------------

function extractProcedures(blocks, entry, succsOf) {
  const inProc = new Array(blocks.length).fill(-1);
  const roots = [entry];
  // Add call-target blocks that are not part of main as subroutine roots.
  for (const b of blocks) {
    if (b.callTarget != null) roots.push(b.callTarget);
  }
  const procs = [];
  const assign = (root) => {
    if (inProc[root] >= 0) return inProc[root];
    const id = procs.length;
    const members = [];
    const visited = new Set();
    const work = [root];
    visited.add(root);
    while (work.length) {
      const x = work.pop();
      members.push(x);
      inProc[x] = id;
      for (const s of succsOf(x)) {
        if (!visited.has(s)) { visited.add(s); work.push(s); }
      }
    }
    procs.push({ root, members });
    return id;
  };
  for (const r of roots) assign(r);
  // Any block not covered (e.g., lone dead code) gets its own procedure.
  for (let i = 0; i < blocks.length; i++) if (inProc[i] < 0) assign(i);
  return { procs, inProc };
}

// ---------------------------------------------------------------------------
// Structural analysis / AST construction
// ---------------------------------------------------------------------------

// The structural analyser walks a procedure's CFG and builds an AST of statements.
// Each statement node is one of:
//   {t:'seq', stmts:[...]}
//   {t:'inst', text}
//   {t:'if', cond, then:[...], else:[...]}
//   {t:'while', cond, body:[...]}
//   {t:'dowhile', cond, body:[...]}
//   {t:'switch', expr, cases:[{v, stmts}], def:[...]}
//   {t:'break'}, {t:'continue'}, {t:'goto', label}
//   {t:'label', name}
//   {t:'call', text}
//   {t:'ret'}, {t:'exit', text}
function structAnalyse(blocks, proc, ctx) {
  const { succsOf, ipdom, loops, loopHeaderOf } = ctx;
  const root = proc.root;
  const emitted = new Set(); // block ids rendered as straight-line/structural nodes
  const loopDone = new Set(); // loop headers whose while/do-while was emitted
  const gotoTargets = new Set(); // block ids that are actually targeted by an emitted `goto`

  const stmts = [];
  const line = (text) => ({ t: 'inst', text });

  function block(id) { return blocks[id]; }
  function labelName(bid) {
    const b = block(bid);
    if (b.labelNames.length) return b.labelNames[0];
    return `bb_${bid}`;
  }

  // Emit straight-line (non-control) instructions of a block.
  // `skip` (optional Set of insts) drops those instructions (used for the fold).
  function emitStraight(b, skip) {
    const out = [];
    const head = b.ctrl == null ? b.insts : b.insts.slice(0, -1);
    for (const inst of head) {
      if (skip && skip.has(inst)) continue;
      out.push(line(renderInst(inst)));
    }
    return out;
  }

  // Emit a call to an intra-script subroutine.
  function emitCall(b) {
    const last = b.ctrl;
    const name = blockNameForCall(b);
    if (last == null || last.mnem !== 'call') return [];
    return [line(`call ${name}(${last.args.slice(1).map(opName).join(', ')})`)];
  }

  function blockNameForCall(b) {
    if (b.callTarget != null) return labelName(b.callTarget);
    const t = b.ctrl.args[0];
    return t.startsWith('label_') ? t : t;
  }

  // The main recursive region emitter.
  // Walks from `entry`, generating statements, stopping when control reaches a
  // block in `exits` (those blocks are not consumed here; they are where the
  // enclosing structure resumes). `topLevel` controls whether block labels are
  // emitted: they are only shown at the procedure's top-level flow (as branch/merge
  // anchors), NOT inside if/else/while bodies.
  function emit(entry, exits, topLevel = false) {
    const out = [];
    let cur = entry;
    let guard = 0;
    while (cur != null && !exits.has(cur) && guard++ < 100000) {
      const b = block(cur);
      if (!b) { if (process.env.STRUCT_DEBUG) console.error(`  [debug] BAD cur=${cur} (exits=${[...exits]})`); out.push({ t: 'goto', label: `bb_${cur}` }); break; }
      // Loop header not yet emitted? loopHeaderOf maps a node to its innermost header.
      const loopHdr = loopHeaderOf && loopHeaderOf.get(cur);
      if (loopHdr != null && loops.has(loopHdr) && !loopDone.has(loopHdr) && cur === loopHdr) {
        const r = emitLoop(loopHdr, exits);
        out.push(r.node);
        loopDone.add(loopHdr);
        cur = r.next;
        continue;
      }
      if (emitted.has(cur)) { out.push({ t: 'goto', label: labelName(cur) }); break; }
      emitted.add(cur);

      // Label retention policy: every non-root block gets a `:`-anchor candidate at
      // the point it is emitted (using its label name, or `bb_N` for unnamed). A final
      // post-pass keeps ONLY the anchors that are actually referenced (by a `goto`, or
      // as a label operand of a retained instruction like `call`/`jmp`/`jcc`), so every
      // reference resolves while the many disassembler branch/merge markers that nothing
      // jumps to are dropped. The procedure root's label is its function name.
      if (cur !== root) {
        out.push({ t: 'label', name: labelName(cur) });
      }

      const ctrl = b.ctrl;
      if (ctrl == null) {
        out.push(...emitStraight(b));
        cur = b.follow;
        continue;
      }
      const m = ctrl.mnem;
      if (m === 'exit' || m === 'exit-script') {
        out.push(...emitStraight(b));
        out.push({ t: 'exit', text: m });
        cur = null; break;
      }
      if (m === 'ret') {
        out.push(...emitStraight(b));
        out.push({ t: 'ret' });
        cur = null; break;
      }
      if (m === 'call') {
        out.push(...emitStraight(b));
        out.push(...emitCall(b));
        cur = b.follow;
        continue;
      }
      if (m === 'jmp') {
        out.push(...emitStraight(b));
        const t = b.follow;
        if (t != null) {
          // A jmp to an un-emitted loop header is the natural loop entry -> fall into it.
          if (loops.has(t) && !loopDone.has(t) && !emitted.has(t)) {
            cur = t; continue;
          }
          // A jmp to an exit boundary -> drop it; the enclosing structure takes over.
          if (exits.has(t)) { cur = null; break; }
          const tb = block(t);
          // A single-predecessor target is a sequential continuation -> flatten (no goto).
          if (tb && tb.preds.size <= 1) { cur = t; continue; }
          gotoTargets.add(t);
          out.push({ t: 'goto', label: labelName(t) });
          cur = t;
          continue;
        }
        cur = null; break;
      }
      if (m === 'jcc') {
        // Fold the immediately-preceding assignment to the tested variable into the
        // if/while header (when present); keep all other instructions. Unexpected
        // shapes are left verbatim (recorded separately).
        const head = b.insts.slice(0, -1);
        const fold = findFoldable(b.ctrl, head);
        const skip = fold ? new Set([fold]) : null;
        out.push(...emitStraight(b, skip));
        const r = structureIfOrFallback(b, exits, fold);
        out.push(...r.stmts);
        cur = r.next;
        continue;
      }
    }
    return out;
  }

  // Try to structure the current block's jcc as if / if-else. Returns {stmts, next}.
  // `fold` (optional) is the instruction that assigns the tested variable and was
  // folded into the condition (its value/references preserved in the header).
  function structureIfOrFallback(b, exits, fold = null) {
    const br = b.branches;
    if (!br) return { stmts: [line(renderTerm(b.ctrl))], next: b.follow };
    const T = br.trueBlock;
    const F = br.falseBlock;
    const varStr = fold ? opName(fold.argsCls[0]) : condForJcc(b.ctrl);
    const rhs = fold ? symbolicRHS(fold) : null;
    const condBase = (rhs != null) ? `${varStr} = ${rhs}` : varStr;
    // Negated condition: keep showing the assignment, then the negated test variable.
    const negCondOf = () => (rhs != null) ? `${condBase}, not ${varStr}` : `not ${varStr}`;
    const join = ipdom.get(b.id);
    const joinReal = (join != null && join !== EXIT) ? join : null;
    const tTerm = T != null && (succsOf(T).length === 0);
    const fTerm = F != null && (succsOf(F).length === 0);

    // Early-return / early-exit: one branch terminates the procedure. Only apply
    // when there is no real reconvergence point (join === virtual EXIT); if a real
    // join exists the join-based rules already handle a terminal join correctly.
    if (joinReal == null && tTerm && !fTerm && F != null) {
      // cond true -> T (returns), cond false -> F (continues).
      const body = emit(T, new Set(), false);
      return { stmts: [{ t: 'if', cond: condBase, then: body, else: [] }], next: F };
    }
    if (joinReal == null && fTerm && !tTerm && T != null) {
      // cond true -> T (continues), cond false -> F (returns).
      const retElse = emit(F, new Set(), false);
      const body = emit(T, new Set(), false);
      return { stmts: [{ t: 'if', cond: condBase, then: body, else: retElse }], next: null };
    }

    // Deterministic join (real block): structure as if / if-else.
    const tIsJoin = joinReal != null && T === joinReal;
    const fIsJoin = joinReal != null && F === joinReal;

    const structureBody = (entryBlock) => {
      if (entryBlock == null) return { stmts: [], next: joinReal };
      const region = collectRegion(entryBlock, new Set([joinReal]).add(b.id), ctx.succsOf);
      if (!region.reachable) return { stmts: [], next: joinReal };
      const stmts = emit(entryBlock, new Set([joinReal]), false);
      return { stmts, next: joinReal };
    };

    if (tIsJoin && fIsJoin) {
      return { stmts: [{ t: 'if', cond: condBase, then: [], else: [] }], next: joinReal };
    }
    if (tIsJoin && !fIsJoin && F != null) {
      // cond true -> join (no-op), cond false -> body. => if (cond) {} else {F} == if(!cond){F}
      const body = structureBody(F);
      return { stmts: [{ t: 'if', cond: negCondOf(), then: body.stmts, else: [] }], next: body.next };
    }
    if (fIsJoin && !tIsJoin && T != null) {
      const body = structureBody(T);
      return { stmts: [{ t: 'if', cond: condBase, then: body.stmts, else: [] }], next: body.next };
    }
    if (!tIsJoin && !fIsJoin && T != null && F != null && joinReal != null) {
      // if/else, both branches reconverge at joinReal.
      const rT = collectRegion(T, new Set([joinReal]), ctx.succsOf);
      const rF = collectRegion(F, new Set([joinReal]), ctx.succsOf);
      if (rT.reachable && rF.reachable) {
        const thenS = emit(T, new Set([joinReal]), false);
        const elseS = emit(F, new Set([joinReal]), false);
        return { stmts: [{ t: 'if', cond: condBase, then: thenS, else: elseS }], next: joinReal };
      }
    }
    // Fallback: emit the block as a conditional branch with gotos, then fall through.
    return fallbackJcc(b, exits);
  }

  function fallbackJcc(b, exits) {
    const br = b.branches;
    const out = [line(renderTerm(b.ctrl))];
    // Represent both edges; fall-through continuation next.
    const next = b.follow;
    if (next != null) return { stmts: out, next };
    return { stmts: out, next: null };
  }

  function renderTerm(inst) {
    return renderInst(inst);
  }

  // Emit a loop whose header is `header`. Returns {node, next}.
  // When the loop's condition is a single assignment to the tested variable (foldable),
  // it is folded into a clean `while <var> = <expr>`. Otherwise a faithful two-step
  // form is used so the condition variable is recomputed each iteration (side-effects
  // preserved): `while true { <cond-computing stmts>; if not <var> break; <body> }`.
  function emitLoop(header, exits) {
    const loop = loops.get(header);
    const exitsSet = loopExits(blocks, loop, ctx.succsOf);
    // The condition block: the loop node whose jcc exits the loop.
    let condBlock = null;
    let condCtrl = null;
    for (const id of loop) {
      const b = block(id);
      const c = b.ctrl;
      if (c && c.mnem === 'jcc') {
        const t = b.branches.trueBlock;
        const f = b.branches.falseBlock;
        if ((t != null && exitsSet.has(t)) || (f != null && exitsSet.has(f))) {
          condBlock = id;
          condCtrl = c;
          break;
        }
      }
    }
    const head = condCtrl ? block(condBlock).insts.slice(0, -1) : [];
    const fold = condCtrl ? findFoldable(condCtrl, head) : null;
    const varStr = fold ? opName(fold.argsCls[0]) : (condCtrl ? condForJcc(condCtrl) : 'true');
    const rhs = fold ? symbolicRHS(fold) : null;
    const isWhile = condBlock != null && condBlock === header;
    // The loop-body entry: from the header's in-loop branch (the branch that stays in loop).
    let bodyEntry = null;
    const hb = block(header);
    const hc = hb.ctrl;
    if (hc && hc.mnem === 'jcc') {
      const t = hb.branches.trueBlock;
      const f = hb.branches.falseBlock;
      if (t != null && loop.has(t)) bodyEntry = t;
      else if (f != null && loop.has(f)) bodyEntry = f;
    }
    if (bodyEntry == null) {
      for (const s of ctx.succsOf(header)) if (loop.has(s)) { bodyEntry = s; break; }
    }
    const bodyExits = new Set([header, ...exitsSet]);
    const bodyStmts = (bodyEntry != null) ? emit(bodyEntry, bodyExits, false) : emitStraight(hb);

    let node;
    if (isWhile && fold && head.length === 1) {
      // Clean folded form: the assignment IS the loop condition (re-evaluated each pass).
      node = { t: 'while', cond: `${varStr} = ${rhs}`, body: bodyStmts };
    } else if (isWhile) {
      node = {
        t: 'while',
        cond: 'true',
        body: [
          ...head.map((i) => line(renderInst(i))),
          { t: 'if', cond: negCond(varStr), then: [{ t: 'break' }], else: [] },
          ...bodyStmts,
        ],
      };
    } else {
      // do-while (test at bottom); the body already carries the recompute just before
      // the back edge, so a plain `do { body } while <var>` is faithful.
      node = { t: 'dowhile', cond: varStr, body: bodyStmts };
    }
    let next = null;
    for (const e of exitsSet) { next = e; break; }
    return { node, next };
  }

  // Top-level: structure the procedure body. Label pruning is a global post-pass
  // over all procedures (see analyseFile) so cross-proc references resolve.
  return emit(root, new Set(), true);
}

// Children of a statement node (for AST traversal).
function stmtChildren(node) {
  switch (node.t) {
    case 'seq': return node.stmts;
    case 'if': return [...node.then, ...node.else];
    case 'while': case 'dowhile': return node.body;
    case 'switch': return [...node.cases.map((c) => c.stmts).flat(), ...node.def];
    default: return [];
  }
}

// Collect the set of label names that are actually referenced: every `goto` target and
// every label that appears as an operand of a retained instruction (e.g. `call label_X`,
// a raw `jmp`/`jcc` that was left in the fallback).
function collectLabelRefs(node, set) {
  if (node.t === 'goto') set.add(node.label);
  else if ((node.t === 'inst' || node.t === 'call') && node.text) {
    const m = /label_[0-9A-Fa-f]+/.exec(node.text);
    if (m) set.add(m[0]);
  }
  for (const c of stmtChildren(node)) collectLabelRefs(c, set);
  return set;
}

// Remove `label:` anchors that nothing references. `refs` is the set of referenced
// label names collected across ALL procedures (so cross-proc references keep anchors).
// `stmts` is the top-level statement ARRAY returned by `emit`.
function pruneUnreferencedLabels(stmts, refs) {
  const cut = (n) => n.t === 'label' && !refs.has(n.name);
  const prune = (n) => {
    if (cut(n)) return null;
    if (n.t === 'seq') n.stmts = n.stmts.map(prune).filter(Boolean);
    else if (n.t === 'if') { n.then = n.then.map(prune).filter(Boolean); n.else = n.else.map(prune).filter(Boolean); }
    else if (n.t === 'while' || n.t === 'dowhile') n.body = n.body.map(prune).filter(Boolean);
    else if (n.t === 'switch') { n.cases = n.cases.map((c) => ({ ...c, stmts: c.stmts.map(prune).filter(Boolean) })); n.def = n.def.map(prune).filter(Boolean); }
    return n;
  };
  const pruned = [];
  for (const n of stmts) {
    if (cut(n)) continue;
    const r = prune(n);
    if (r) pruned.push(r);
  }
  stmts.length = 0;
  stmts.push(...pruned);
}

// Attach ctrl metadata to every block based on its last instruction.
function attachCtrl(blocks) {
  for (const b of blocks) {
    const last = b.insts[b.insts.length - 1];
    b.ctrl = last && TERMINATORS.has(last.mnem) ? last : null;
  }
}

// ---------------------------------------------------------------------------
// Graphviz DOT + JSON output
// ---------------------------------------------------------------------------

function nodeLabel(b) {
  const names = (b.labelNames && b.labelNames.length) ? b.labelNames.join(',') : `bb_${b.id}`;
  return names;
}

function toDot(blocks, proc, edges) {
  const all = proc ? new Set(proc.blockIds || proc.members || []) : null;
  const lines = ['digraph CFG {'];
  lines.push('  rankdir=TB;');
  lines.push('  node [shape=box, fontname="monospace"];');
  for (const b of blocks) {
    if (all && !all.has(b.id)) continue;
    const body = b.insts.map(i => renderInst(i)).join('\\l');
    lines.push(`  n${b.id} [label="${nodeLabel(b)}\\l${body}\\l"];`);
  }
  for (const b of blocks) {
    if (all && !all.has(b.id)) continue;
    for (const s of b.succs) {
      if (all && !all.has(s)) continue;
      const lbl = b.branches && b.branches.trueBlock === s ? 'T' : (b.branches && b.branches.falseBlock === s ? 'F' : '');
      lines.push(`  n${b.id} -> n${s}${lbl ? ` [label="${lbl}"]` : ''};`);
    }
  }
  lines.push('}');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Pretty printer (render the AST as pseudocode)
// ---------------------------------------------------------------------------

// Return a single `if` node if the statement list is exactly one if (possibly wrapped
// in a one-element seq), otherwise null. Used to fold `else { if }` -> `else if`.
function foldElseIf(stmts) {
  if (stmts.length === 1) {
    let s = stmts[0];
    if (s.t === 'seq' && s.stmts.length === 1) s = s.stmts[0];
    if (s.t === 'if') return s;
  }
  return null;
}

// Render an `else if <cond> ...` node at the given indentation, continuing the fold.
function renderElseIf(node, out, indent) {
  const pad = '    '.repeat(indent);
  out.push(`${pad}else if ${node.cond}`);
  if (node.then.length) render({ t: 'seq', stmts: node.then }, out, indent + 1);
  if (node.else.length) {
    const folded = foldElseIf(node.else);
    if (folded != null) renderElseIf(folded, out, indent);
    else {
      out.push(pad + 'else');
      render({ t: 'seq', stmts: node.else }, out, indent + 1);
    }
  }
}

function render(node, out, indent) {
  const pad = '    '.repeat(indent);
  switch (node.t) {
    case 'seq':
      for (const s of node.stmts) render(s, out, indent);
      break;
    case 'inst':
      out.push(pad + node.text);
      break;
    case 'if':
      out.push(`${pad}if ${node.cond}`);
      if (node.then.length) render({ t: 'seq', stmts: node.then }, out, indent + 1);
      if (node.else.length) {
        // Fold `else { if ... }` into `else if ...` to reduce nesting in if/else-if chains.
        const folded = foldElseIf(node.else);
        if (folded != null) {
          renderElseIf(folded, out, indent);
        } else {
          out.push(pad + 'else');
          render({ t: 'seq', stmts: node.else }, out, indent + 1);
        }
      }
      break;
    case 'while':
      out.push(`${pad}while ${node.cond}`);
      if (node.body.length) render({ t: 'seq', stmts: node.body }, out, indent + 1);
      break;
    case 'dowhile':
      out.push(`${pad}do`);
      if (node.body.length) render({ t: 'seq', stmts: node.body }, out, indent + 1);
      out.push(`${pad}while ${node.cond}`);
      break;
    case 'switch':
      out.push(`${pad}switch ${node.expr}`);
      for (const c of node.cases) {
        out.push(`${pad}    case ${c.v}`);
        render({ t: 'seq', stmts: c.stmts }, out, indent + 2);
      }
      if (node.def.length) {
        out.push(`${pad}    default`);
        render({ t: 'seq', stmts: node.def }, out, indent + 2);
      }
      break;
    case 'break':
      out.push(pad + 'break');
      break;
    case 'continue':
      out.push(pad + 'continue');
      break;
    case 'goto':
      out.push(pad + `goto ${node.label}`);
      break;
    case 'label':
      out.push(pad + `${node.name}:`);
      break;
    case 'call':
      out.push(pad + node.text);
      break;
    case 'ret':
      out.push(pad + 'ret');
      break;
    case 'exit':
      out.push(pad + (node.text || 'exit'));
      break;
    default:
      out.push(pad + JSON.stringify(node));
  }
}

// ---------------------------------------------------------------------------
// Driver
// ---------------------------------------------------------------------------

function options(raw) {
  const opts = { files: [], dot: null, json: null, raw: false, dir: null, out: '.', suffix: '.struct.txt' };
  for (let i = 0; i < raw.length; i++) {
    const a = raw[i];
    if (a === '--dot') opts.dot = raw[++i];
    else if (a === '--json') opts.json = raw[++i];
    else if (a === '--raw') opts.raw = true;
    else if (a === '--dir') opts.dir = raw[++i];
    else if (a === '--out') opts.out = raw[++i];
    else if (a === '--suffix') opts.suffix = raw[++i];
    else if (a === '--help' || a === '-h') opts.help = true;
    else if (a.startsWith('-')) { /* ignore unknown flags */ }
    else opts.files.push(a);
  }
  return opts;
}

function analyseFile(file, opts) {
  const t0 = process.hrtime.bigint();
  CURRENT_FILE = file;
  const text = fs.readFileSync(file, 'utf8');
  const sc = parse(text);
  const tParse = (process.hrtime.bigint() - t0) / 1000000n;
  const { blocks, blockOfInstr } = buildBlocks(sc);
  attachCtrl(blocks);
  const succsOf = (id) => [...(blocks[id].succs)];
  const tBlocks = (process.hrtime.bigint() - t0) / 1000000n - tParse;
  if (process.env.STRUCT_TIMING) console.error(`  [timing] ${path.basename(file)} insts=${sc.insts.length} blocks=${blocks.length} build=${tBlocks}ms`);

  const { procs, inProc } = extractProcedures(blocks, 0, succsOf);
  const ctx = { blocks, succsOf, labelOf: sc.labelOf };

  const procResults = [];
  for (const proc of procs) {
    const nodes = proc.members;
    const entry = proc.root;
    const domInfo = computeDominators(nodes, entry, succsOf);
    const post = computePostdominators(nodes, succsOf);
    const ipdom = post.ipdom;
    if (process.env.STRUCT_TIMING) console.error(`  [timing] ${path.basename(file)} insts=${sc.insts.length} blocks=${blocks.length} proc=${proc.root} nodes=${nodes.length}`);
    const loops = findNaturalLoops(blocks, entry, succsOf, domInfo);
    if (process.env.STRUCT_DEBUG) {
      console.error(`  [debug] proc root=${entry} nodes=${nodes.join(',')}`);
      for (const [h, l] of loops) console.error(`  [debug]   loop header=${h} members=${[...l].join(',')}`);
    }
    // loopHeaderOf: node -> header of the innermost loop containing it.
    const loopHeaderOf = new Map();
    for (const [hdr, loop] of loops) for (const id of loop) {
      const cur = loopHeaderOf.get(id);
      if (cur == null || loop.size < (loops.get(cur)?.size || Infinity)) loopHeaderOf.set(id, hdr);
    }
    const pctx = { ...ctx, ipdom, loops, loopHeaderOf };
    const stmts = structAnalyse(blocks, proc, pctx);
    procResults.push({ root: entry, blockIds: nodes, stmts });
  }

  // Label retention, GLOBAL pass: a `call`/`goto`/`jcc` in one procedure can reference
  // a block that lives in another procedure (or is flow-reachable there). So we collect
  // references across ALL procedures, then keep a label anchor only if something
  // (anywhere) references it. This makes cross-proc references resolve.
  const globalRefs = new Set();
  for (const p of procResults) collectLabelRefs({ t: 'seq', stmts: p.stmts }, globalRefs);
  for (const p of procResults) pruneUnreferencedLabels(p.stmts, globalRefs);

  // References completeness: any referenced label that got no anchor / proc (its block
  // was dropped by a fallback branch) is surfaced as a stub section, so `call`/`jcc`
  // references always have a visible target. Only emit the section if there are such.
  const defined = new Set();
  for (const p of procResults) {
    if (p.isStub) continue;
    const rb = blocks[p.root];
    if (rb) for (const n of rb.labelNames) defined.add(n); // procedure name (function boundary)
  }
  for (const p of procResults) collectLabelNodes({ t: 'seq', stmts: p.stmts }, defined); // shown anchors
  const stubs = [];
  for (const lab of globalRefs) {
    if (defined.has(lab)) continue;
    const iidx = sc.labelOf.get(lab);
    if (iidx == null || iidx >= blockOfInstr.length || blockOfInstr[iidx] == null) continue;
    const bid = blockOfInstr[iidx];
    const b = blocks[bid];
    const body = b.insts.map((i) => line0(renderInst(i)));
    stubs.push({ t: 'label', name: lab });
    stubs.push(...body);
    stubs.push({ t: 'ret' });
    defined.add(lab);
  }
  if (stubs.length) procResults.push({ root: -1, blockIds: [], stmts: stubs, isStub: true });

  return { file, sc, blocks, procs: procResults };
}

function collectLabelNodes(node, set) {
  if (node.t === 'label') set.add(node.name);
  for (const c of stmtChildren(node)) collectLabelNodes(c, set);
}

const line0 = (text) => ({ t: 'inst', text });

function renderProcedure(proc) {
  const out = [];
  render({ t: 'seq', stmts: proc.stmts }, out, 0);
  return out;
}

function main() {
  const opts = options(process.argv.slice(2));
  if (opts.help) {
    console.log(`Usage:
  node re/structured_cfg.js <src.txt> [--dot out.dot] [--json out.json] [--raw]
  node re/structured_cfg.js --dir <srcdir> [--out <dir>] [--suffix .struct.txt]`);
    process.exit(0);
  }
  let files = opts.files;
  if (opts.dir) {
    files = fs.readdirSync(opts.dir).filter(f => f.endsWith('.txt')).map(f => path.join(opts.dir, f)).sort();
  }
  if (files.length === 0) { console.error('No input files.'); process.exit(1); }

  for (const file of files) {
    try {
      const res = analyseFile(file, opts);
      if (opts.dot) {
        const dot = toDot(res.blocks, res.procs[0], null);
        fs.writeFileSync(opts.dot, dot);
        console.log(`# dot -> ${opts.dot}`);
      }
      if (opts.json) {
        fs.writeFileSync(opts.json, JSON.stringify({
          file: file,
          procedures: res.procs.map(p => ({ root: p.root, blocks: p.blockIds, stmts: p.stmts })),
        }, null, 2));
        console.log(`# json -> ${opts.json}`);
      }
      // Render each procedure.
      const outLines = [];
      outLines.push(`;; ${path.basename(file)}`);
      outLines.push(`;; local_vars = ${JSON.stringify(res.sc.locals || [])}`);
      for (const p of res.procs) {
        if (p.isStub) {
          outLines.push(';; --- referenced targets not reachable in structure (stubs) ---');
          outLines.push(...renderProcedure(p));
          outLines.push('');
          continue;
        }
        outLines.push(`;; --- procedure root=bb_${p.root} (${res.blocks[p.root].labelNames.join(',') || 'entry'}) ---`);
        outLines.push(...renderProcedure(p));
        outLines.push('');
      }
      const text = outLines.join('\n');
      if (opts.dir && opts.out) {
        const base = path.basename(file, path.extname(file));
        const dest = path.join(opts.out, base + opts.suffix);
        fs.writeFileSync(dest, text);
        console.log(`# -> ${dest}`);
      } else {
        console.log(text);
      }
    } catch (e) {
      console.error(`!! ${file}: ${e.message}`);
      if (process.env.STRUCT_DEBUG) console.error(e.stack);
    }
  }

  if (unexpected.size) {
    console.error(`\n[record] ${unexpected.size} instruction shape(s) kept VERBATIM (not rewritten):`);
    for (const [key, info] of unexpected) {
      console.error(`  ${info.count}x  ${key}   e.g. ${info.example}   (${info.file})`);
    }
  }
}

main();
